package com.azmetov.playlistmaker.other

object Constants {
    const val THEME_SWITCHER_PREFERENCES = "THEME_SWITCHER_PREFERENCES"
    const val THEME_SWITCHER_KEY = "THEME_SWITCHER_KEY"
    const val SEARCH_TRACKS_PREFS = "SEARCH_TRACKS_PREFS"
    const val COUNT_OF_TRACKS = 10
    const val TRACKS_HISTORY_KEY = "TRACKS_HISTORY_KEY"
    const val IS_PLAYER_ACTIVITY_OPENED = "IS_PLAYER_ACTIVITY_OPENED"
    const val TRACK_DATA = "TRACK_DATA"
    const val PLAYER_SHARED_PREFS = "PLAYER_SHARED_PREFS"
}
